/// Flutter icons ToTCustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ToTCustomIcons
///      fonts:
///       - asset: fonts/ToTCustomIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class ToTCustomIcons {
  ToTCustomIcons._();

  static const _kFontFam = 'ToTCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData logo_cmyk = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_text_cmyk = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_on = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_off = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_rgb = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_cmyk_1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_rgb_1 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_text_rgb = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_on = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_off = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_off = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_on = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notify = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slide_bookmark_on = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slide_bookmark_off = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_on = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_off = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
